config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do

  get 'projects/:id/project_roles/:role_id/edit', :to => 'project_roles#edit', as: :edit_project_role
  get 'projects/:id/project_roles', :to => 'project_roles#index', as: :project_roles
  get 'projects/:id/project_roles/:role_id/reset', :to => 'project_roles#reset', as: :reset_project_role
  post 'projects/:id/project_roles/:role_id/save', :to => 'project_roles#save', as: :save_project_role
  patch 'projects/:id/project_roles/:role_id/save', :to => 'project_roles#save'

end

app/models/project_role.rb
class ProjectRole < ActiveRecord::Base
  unloadable

  belongs_to :role

  attr_accessible :project_id,
    :role_id,
    :name,
    :position,
    :assignable,
    :builtin,
    :permissions,
    :issues_visibility,
    :users_visibility

  serialize :permissions, ::Role::PermissionsAttributeCoder

  def setable_permissions
    setable_permissions = Array.new
    Setting.plugin_redmine_overwriting_roles["permissions"].each do |setting|
      setable_permissions += Redmine::AccessControl.permissions.select {|perm| perm.name == setting.to_sym}
    end
    setable_permissions
  end

  def permissions=(perms)
    perms = perms.collect {|p| p.to_sym unless p.blank? }.compact.uniq if perms
    write_attribute(:permissions, perms)
  end

end

app/controllers/project_roles_controller.rb
class ProjectRolesController < ApplicationController

  before_filter :find_project
  before_filter :find_role, only: [:save, :edit, :reset]
  before_filter :assign_project_role, only: [:edit, :save, :reset]
  before_filter :check_permissions

  def index
    @roles = Role.all
  end

  def edit
    render partial: 'edit', :layout => false if request.xhr?
  end

  def save
    @project_role.permissions = params[:project_role][:permissions]
    if @project_role.save
      flash[:notice] = l(:notice_successful_update)
      redirect_to settings_project_path(:tab => 'roles')
    else
      render :action => 'edit'
    end
  end

  def reset
    @project_role.permissions = @role.permissions
    @project_role.save
    flash[:notice] = l(:notice_successfull_reset)
    redirect_to edit_project_role_path(@project, @role)
  end

  private
  def build_project_role
    ProjectRole.new(@role.attributes.merge({project_id: @project.id, role_id: @role.id}))
  end

  def find_project_role
    @role.project_roles.where(project_id: @project.id).first
  end

  def find_role
    @role = Role.find(params[:role_id])
  end

  def assign_project_role
    @project_role = find_project_role || build_project_role
  end

  def check_permissions
    unless User.current.admin? || User.current.allowed_to?(:manage_roles, @project)
      redirect_to home_path
    end
  end
end

app/views/project_roles/_edit.html.erb
<h2><%= @role.name %></h2>

<%= labelled_form_for @project_role, :url => save_project_role_path(@project, @role) do |f| %>
<%= render :partial => 'form', :locals => { :f => f } %>
<%= submit_tag l(:button_save) %>
<% end %>

app/views/project_roles/_form.html.erb
<%= error_messages_for 'project_role' %>

<h3><%= l(:label_permissions) %></h3>
<div class="box tabular" id="permissions">
  <% perms_by_module = @project_role.setable_permissions.group_by {|p| p.project_module.to_s} %>
  <% perms_by_module.keys.sort.each do |mod| %>
  <fieldset><legend><%= mod.blank? ? l(:label_project) : l_or_humanize(mod, :prefix => 'project_module_') %></legend>
    <% perms_by_module[mod].each do |permission| %>
    <label class="floating">
      <%= check_box_tag 'project_role[permissions][]', permission.name, (@project_role.permissions.include? permission.name), :id => nil %>
      <%= l_or_humanize(permission.name, :prefix => 'permission_') %>
    </label>
    <% end %>
  </fieldset>
  <% end %>
  <br /><%= check_all_links 'permissions' %>
  <br/><%= link_to l(:restore_default_permissions), reset_project_role_path(@project, @role) %>
  <%= hidden_field_tag 'project_role[permissions][]', '' %>
</div>

app/views/project_roles/edit.html.erb
<%= render :partial => 'edit' %>

app/views/project_roles/index.html.erb
<div class="project-roles-wrapper" style="width:40%;">

  <% @roles = Role.all %>

  <table class='list'>
    <thead>
      <tr>
        <th>Role</th>
      </tr>
    </thead>
    <tbody>
      <% @roles.each do |role| %>
      <tr>
        <td class='name'><%= link_to role.name, edit_project_role_path(@project, role) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/projects/settings/_roles.html.erb
<div class="project-roles-wrapper" id="content" style="width:40%;">
  <div id="roles">
    <% @roles = Role.all %>

    <table class='list'>
      <thead>
        <tr>
          <th colspan="2">Role</th>
        </tr>
      </thead>
      <tbody>
        <% @roles.each do |role| %>
        <tr>
          <td class='name'><%= role.name %></td>
          <td class="buttons" style="width: 30px">
            <%= link_to l(:button_edit),
            edit_project_role_path(@project, role),
            :class => 'icon icon-edit'%>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/settings/_project_role_settings.html.erb
<%= error_messages_for 'project_role' %>

<h3><%= l(:label_permissions) %></h3>
<div class="box tabular" id="permissions">
  <% perms_by_module = Redmine::AccessControl.permissions.group_by {|p| p.project_module.to_s} %>
  <% perms_by_module.keys.sort.each do |mod| %>
  <fieldset><legend><%= mod.blank? ? l(:label_project) : l_or_humanize(mod, :prefix => 'project_module_') %></legend>
    <% perms_by_module[mod].each do |permission| %>
    <label  style="font-weight: normal; margin-left: 0px; text-align: left; width: 270px;">
      <%= check_box_tag 'settings[permissions][]', permission.name, (@settings['permissions'].include? permission.name.to_s) %>
      <%= l_or_humanize(permission.name, :prefix => 'permission_') %>
    </label>
    <% end %>
  </fieldset>
  <% end %>
  <br /><%= check_all_links 'permissions' %>
</div>